[versions]
openapi-generator = "7.12.0"
moshi = "1.15.1"
kotest = "5.9.0"
maven-publish = "0.29.0"

[libraries]
moshi-kotlin = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshi" }
moshi-adapters = { group = "com.squareup.moshi", name = "moshi-adapters", version.ref = "moshi" }
kotest-junit5 = { group = "io.kotest", name = "kotest-runner-junit5", version.ref = "kotest" }
kotest-assertions-core = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }
kotest-assertions-json = { group = "io.kotest", name = "kotest-assertions-json", version.ref = "kotest" }

[plugins]
openapi-generator = { id = "org.openapi.generator", version.ref = "openapi-generator" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
